# Generated by Django 5.0.7 on 2024-07-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_decade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decade',
            name='artist',
        ),
    ]
